### PR TITLE
CARTree returning nodeId of the leaf for a classified sample

### PR DESCRIPTION
**Pull request by inglada**
Hi,
I have started having a look at how to implement a solution for 
[this issue](https://github.com/Shark-ML/Shark/issues/211). The test for RFClassifier shows how to use it. I guess that the relabelTreeWithNodeIds() method should only be available for CARTrees where LabelType is unsigned int, but this is just an experiment.
Thanks for your time.

### CODE REVIEW

**Comment by Ulfgard** [comment]
Hi, 
why did you close this? i would still like to pull parts of it (the nodeid thingy)
i think i might be able to provide you with a working code snippet for tree generation later this week, but currently i am a bit stressed :(

**Comment by inglada** [comment]
Hi,

I removed the relabelling function so that you can pull from my code. I have implemented the tree generation elsewhere.

I can keep it for me, as you suggest in the issue thread, but I thought it could be useful to somebody else. What do you suggest for this kind of contribution?

Thanks.

**Comment by Ulfgard** [comment]
looks really good and i think it is a good contribution complementing the tree generation routines. Very nice.

The only thing is that the indentations are not correct. we use tabs and below every if should be a level of indentation. Should i fix this or do you want to do it?

**Comment by inglada** [comment]
HI,
Thanks. You can fix the indentation if it is not much work for you. Otherwise, I'll do it. What indentation style are you using (Stroustrup?)?

**Comment by Ulfgard** [comment]
Done. Thank you!

We have no particular stzle that we enforce, the only rule is that everything following a { should be indented once (except class scopes and singe-line ifs). And we indent with tabs. Beyond that, there are no fixed rules.

**Pull request merged**
